# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://tcfraser.com
paginate:         2
baseurl:          /
author:
  name:           TC Fraser
  email:          tcfraser237@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tcfraser/tcfraser.github.io
