# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            TC Fraser
description:      'An amalgamation of unrelated topics and ideas I was interested in at some point.'
url:              http://tcfraser.com
baseurl:          /

author:
  name:           'TC Fraser'
  url:            https://tcfraser.com

paginate:         5

github:
  repo:           https://github.com/tcfraser

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            latex: "mathjax"
            excerpt_separator: "<!--more-->"
