# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            TC Fraser
tagline:          ''
description:      'An amalgamation of unrelated topics and ideas I was interested in at some point.'
url:              http://tcfraser.com
baseurl:          /

author:
  name:           'TC Fraser'
  url:            https://tcfraser.com

paginate:         5

github:
  repo:           https://github.com/tcfraser
